server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(79MrIeXqna2hR0XnVdthbzRK2rFjmHI7BCVC5ykl54s4pkWuyxgNaUXdRjGhsDpB9PxxNwoCzjkEPbmFO/NTwOB2NhPF9JT2gEKrBpnAXR41zyC8dpxpm66xDKYkORHvaYQI/I5CRbJW9+pBeOmjUKwNurBviSyUc4KHUXIPh1VeLbIQE5NDlJJlyi3GfyVw)
    username: ENC(MbGX0toTGl/MRru6dPDcng==)
    password: ENC(ZZjZ0NIxG2mwTYEcazez21PGrKthiCXn)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

